apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dnaprawa

resources:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=booking-microservices
images:
- name: ghcr.io/dnaprawa/cicd-from-scratch-flight
  newTag: sha-e84961061ea68e1bc5c0a340ae08975970f08d85
- name: ghcr.io/dnaprawa/cicd-from-scratch-frontend
  newTag: sha-e84961061ea68e1bc5c0a340ae08975970f08d85
