apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dnaprawa

resources:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=booking-microservices
images:
- name: ghcr.io/dnaprawa/cicd-from-scratch-flight
  newTag: sha-04d54b5b99af1a60f3e466376af9235fcdc73c94
- name: ghcr.io/dnaprawa/cicd-from-scratch-frontend
  newTag: sha-04d54b5b99af1a60f3e466376af9235fcdc73c94
