---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: booking-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/dnaprawa/cicd-from-scratch-frontend:sha-c755dd94ab8b563682f1d43a54d846216ff61d80
          name: frontend
          ports:
            - containerPort: 8080
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: docker
          resources:
            requests:
              memory: 64Mi
              cpu: 15m
            limits:
              memory: 512Mi
              cpu: 256m
